FRINXio/conductor

ui/package-lock.json
ui/package.json
ui/src/components/workflow/executions/WorkflowDetails.js

"Unescape" button added to workflow input and output in detailed view of workflow or task. It decodes the escaped JSON string to make it more human readable

Added 'unescape' button next to workflow input/output

---

ui/src/actions/WorkflowActions.js
ui/src/api/wfe.js
ui/src/components/workflow/JSONTab.js
ui/src/components/workflow/WorkflowMetaDetails.js
ui/src/components/workflow/WorkflowMetaList.js
ui/src/components/workflow/executions/WorkflowDetails.js
ui/src/styles/main.css

An edit button added next to JSON in Workflow meta. This button makes the JSON editable.
After hitting "Save" the JSON is pushed to the server and workflow meta is updated.
The "editor" also will show an error on screen if it can't parse the edited JSON file (e.g. if the JSON entered is invalid)

Added edit button next to Workflow meta JSON

---

ui/src/components/workflow/executions/WorkflowDetails.js

Added the ability to refresh the diagram in a currently executing workflow.
Either by clicking a button or by setting a timer for auto-refresh.

Added WorkFlow refresh functionality

---

docs/docs/technicaldetails.md
redis-persistence/src/main/java/com/netflix/conductor/dao/RedisWorkflowModule.java
redis-persistence/src/main/java/com/netflix/conductor/dao/dynomite/queue/DynoQueueDAO.java
redis-persistence/src/main/java/com/netflix/conductor/dyno/RedisQueuesProvider.java
redis-persistence/src/main/java/com/netflix/conductor/dyno/RedisQueuesShardingStrategyProvider.java
test-harness/src/test/java/com/netflix/conductor/tests/utils/TestModule.java

We need to wait for upstream to review: https://github.com/Netflix/conductor/pull/1728

LocalOnly sharding strategy for dyno queues

---

client/python/.gitignore
client/python/README.md
client/python/conductor/ConductorWorker.py
client/python/conductor/FrinxConductorWrapper.py
client/python/conductor/__init__.py
client/python/conductor/conductor.py
client/python/setup.py

----
----
Part of the conductor python package creation process. Back ported changes from uniflow-micors

Adjust python client for frinx use case

---

.github/workflows/pypi-publish.yml
client/python/setup.py

Describe the changes made in this PR.
Steps to test or reproduce.

Add pypi workflow

---

.github/workflows/pypi-publish.yml
client/python/setup.py

Describe the changes made in this PR.
Steps to test or reproduce.

Update workflows ubuntu base image

---

core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java

Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
Describe the changes made in this PR.
Steps to test or reproduce.

Disable ownerEmail test

---

client/python/conductor/FrinxConductorWrapper.py
client/python/setup.py

Frinx Wrapper with multi-thread options

---

polyglot-clients/python/conductor/FrinxConductorWrapper.py

Signed-off-by: vklevlanyk <vklevlanyk@frinx.io>
Describe the changes made in this PR.
Steps to test or reproduce.

Fix external storage location headers

---

azureblob-storage/dependencies.lock
build.gradle
cassandra-persistence/dependencies.lock
client-spring/dependencies.lock
client/dependencies.lock
common/dependencies.lock
contribs/dependencies.lock
core/dependencies.lock
dependencies.lock
es6-persistence/dependencies.lock
grpc-client/dependencies.lock
grpc-server/dependencies.lock
grpc/dependencies.lock
mysql-persistence/dependencies.lock
postgres-persistence/dependencies.lock
redis-lock/dependencies.lock
redis-persistence/dependencies.lock
rest/dependencies.lock
server/dependencies.lock
test-harness/dependencies.lock
zookeeper-lock/dependencies.lock

Signed-off-by: Vasyl <vklevlanyk@frinx.io>

Update log4j to 2.17 to avoid DoS vulnerability

---

postgres-external-storage/src/main/java/com/netflix/conductor/postgres/config/PostgresPayloadConfiguration.java

Do not use 3 distinct pools:
1) postgresql storage
2) external payload storage based on psql - Flyway migration
3) external payload storage based on psql - Normal operation

Reuse single connection pool for external storage service

---

postgres-external-storage/src/main/java/com/netflix/conductor/postgres/config/PostgresPayloadConfiguration.java

Fix formatting issue during building docker image

Fix formatting

---

core/src/main/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraint.java
core/src/test/java/com/netflix/conductor/validations/WorkflowTaskTypeConstraintTest.java
test-harness/src/test/groovy/com/netflix/conductor/test/integration/DoWhileSpec.groovy
test-harness/src/test/resources/do_while_sub_workflow_integration_test.json

* Initial cut
Initial cut
* Format plugin
----
----
Issue #
----

Added support for sub workflow in loop task (#2807)

---

docker/server/bin/startup.sh
docker/server/config/log4j-file-appender.properties
docker/server/config/log4j.properties

- configure path via env variable
- add default properties

Enable logs configuration via log4j properties

---

contribs/src/main/java/com/netflix/conductor/contribs/tasks/json/JsonJqTransform.java

Change implementation of jsonJQ task to be able to read input from external storage

JsonJQ task support external storage input

---

core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java

repair inconsistent subworkflow task (#3183)

---

common/src/test/java/com/netflix/conductor/common/tasks/TaskDefTest.java
common/src/test/java/com/netflix/conductor/common/workflow/WorkflowDefValidatorTest.java
postgres-external-storage/src/main/java/com/netflix/conductor/postgres/config/PostgresPayloadConfiguration.java
postgres-external-storage/src/main/java/com/netflix/conductor/postgres/storage/PostgresPayloadStorage.java
postgres-external-storage/src/test/java/com/netflix/conductor/postgres/storage/PostgresPayloadStorageTest.java

Signed-off-by: Vasyl Klevlanyk <vklevlanyk@frinx.io>
----
----
Fix format
----

- Fix format for Postgres External Storage

---

core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowRepairService.java
core/src/test/java/com/netflix/conductor/core/reconciliation/TestWorkflowRepairService.java

fix subworkflow output during repair (#3232)

---

.github/workflows/verify.yml
build.gradle
contribs/src/main/java/com/netflix/conductor/contribs/tasks/json/JsonJqTransform.java
core/src/main/java/com/netflix/conductor/core/dal/ExecutionDAOFacade.java
core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java
core/src/main/java/com/netflix/conductor/core/execution/mapper/SubWorkflowTaskMapper.java
core/src/main/java/com/netflix/conductor/core/execution/tasks/Join.java
core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java
core/src/main/java/com/netflix/conductor/model/TaskModel.java
core/src/test/java/com/netflix/conductor/service/MetadataServiceTest.java
docker/server/Dockerfile
gradle.properties
grpc/src/main/java/com/netflix/conductor/grpc/AbstractProtoMapper.java
grpc/src/main/proto/model/workflowsummary.proto
test-harness/src/test/groovy/com/netflix/conductor/test/integration/JsonJQTransformSpec.groovy

Also enable unit tests
+ run them as a verify job on PR

Fix mising output after join

---

core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
core/src/test/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtilsTest.java

Signed-off-by: Simon Misencik <simon.misencik@gmail.com>
----
----
Issue #
----

Fix unit test in ExternalPayloadStorageUtils

---

common/src/main/java/com/netflix/conductor/common/utils/ExternalPayloadStorage.java
core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java
core/src/test/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtilsTest.java
dependencies.gradle
server/src/main/resources/application.properties

Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
----
----
Issue #
----

Cherry-pick: PSQL External payload storage deduplication

---

.github/workflows/docker-publish.yml
docker/server/Dockerfile

Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
----
----
Issue #
----

Set version to 2.0.0-SNAPSHOT

---

frinx/README.md
frinx/calculateDurationOfWorkflowExecution.sh

+ update submodule
Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
----
- [ x] Other (please describe):
----
Issue #
----

Add script to measure workflow execution

---

.github/workflows/verify.yml
dependencies.gradle
server/build.gradle
server/src/main/resources/application.properties
settings.gradle

Reenable psql archive

---

.github/workflows/verify.yml
dependencies.gradle
server/build.gradle
server/src/main/resources/application.properties
settings.gradle

Revert "Reenable psql archive"

---

.github/workflows/verify.yml
dependencies.gradle
server/build.gradle
server/src/main/resources/application.properties
settings.gradle

For version 2.1.0 we want the psql archive working instead of ES
This reverts commit 1eadbedafdfbe3e2c24d1911d0118864cad5d8fd.
----
----
Issue #
----

Revert "Revert "Reenable psql archive""

---

docker/server/config/config-local.properties

Make default config in docker image use postgres

---

core/src/main/java/com/netflix/conductor/core/sync/local/LocalOnlyLock.java
core/src/test/java/com/netflix/conductor/core/sync/local/LocalOnlyLockTest.java

It did not support reentrancy.
This was a problem at least in following case:
worker -> updateTask -> throw new TerminateWorkflowException -> terminateWorkflow
The lock was acquired twice during above execution order. With no reentrancy, the second lock (wf terminateion) failed and sweeper had to wait until the first lock (task update) was released and only then workflow could be terminated.
----
----
Issue #
----

Make LocalOnlyLock reentrant

---

client/src/main/java/com/netflix/conductor/client/http/EventClient.java
core/src/main/java/com/netflix/conductor/core/execution/DeciderService.java
test-harness/src/test/groovy/com/netflix/conductor/test/integration/SimpleWorkflowSpec.groovy

Avoid exception message set to 'null'

---

.github/workflows/pypi-publish-stable-1-0-X.yml
.github/workflows/pypi-publish.yml

Pypi timeout

---

.github/workflows/docker-publish.yml
docker/server/Dockerfile

Add labels into dockerfile

---

client/src/main/java/com/netflix/conductor/client/http/WorkflowClient.java
rest/src/main/java/com/netflix/conductor/rest/controllers/WorkflowResource.java
rest/src/test/java/com/netflix/conductor/rest/controllers/WorkflowResourceTest.java
test-harness/src/test/java/com/netflix/conductor/test/integration/http/AbstractHttpEndToEndTest.java

- mitigation of plain binding of a POJO type vulnerability
- updated tests and WorkflowClient
Type: Improvement
JIRA: DEP-609

Added @RequestBody

---

.github/workflows/openapi_diff.yml

openapi diff

---

.github/workflows/docker-publish.yml

Temporary enable workflow dispatch on docker publish

---

.github/workflows/verify.yml

Update RBAC GHA

---

.github/workflows/verify.yml

Update Github Actions for RBAC

---

rest/src/main/java/com/netflix/conductor/rest/rbac/RbacHttpFilter.java

Type: Improvement
Signed-off-by: jmasar <jmasar@frinx.io>

Handle requests not using RBAC

---

docker/server/config/log4j-cluster.properties

Add log4j into docker image
